# Tuned
MountainCarContinuous-v0:
  n_timesteps: 300000
  policy: 'MlpPolicy'
  noise_type: 'ornstein-uhlenbeck'
  noise_std: 0.5

Pendulum-v1:
  n_timesteps: 20000
  policy: 'MlpPolicy'
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: -1
  train_freq: [1, "episode"]
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"

LunarLanderContinuous-v2:
  n_timesteps: !!float 3e5
  policy: 'MlpPolicy'
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: -1
  train_freq: [1, "episode"]
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"

BipedalWalker-v3:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: -1
  train_freq: [1, "episode"]
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"

# To be tuned
BipedalWalkerHardcore-v3:
  n_timesteps: !!float 1e7
  policy: 'MlpPolicy'
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: -1
  train_freq: [1, "episode"]
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"

# Tuned
HalfCheetahBulletEnv-v0: &pybullet-defaults
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: 1
  train_freq: 1
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"

# Tuned
AntBulletEnv-v0:
  <<: *pybullet-defaults
  learning_rate: !!float 7e-4
  policy_kwargs: "dict(net_arch=[400, 300])"

# Tuned
HopperBulletEnv-v0:
  <<: *pybullet-defaults
  train_freq: 64
  gradient_steps: 64
  batch_size: 256
  learning_rate: !!float 7e-4

# Tuned
Walker2DBulletEnv-v0:
  <<: *pybullet-defaults
  batch_size: 256
  learning_rate: !!float 7e-4

# TO BE tested
HumanoidBulletEnv-v0:
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: -1
  train_freq: [1, "episode"]
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"

# Tuned
ReacherBulletEnv-v0:
  <<: *pybullet-defaults
  n_timesteps: !!float 3e5


# To be tuned
InvertedDoublePendulumBulletEnv-v0:
  <<: *pybullet-defaults
  n_timesteps: !!float 1e6

# To be tuned
InvertedPendulumSwingupBulletEnv-v0:
  <<: *pybullet-defaults
  n_timesteps: !!float 3e5

# === Mujoco Envs ===

HalfCheetah-v3: &mujoco-defaults
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_starts: 10000
  noise_type: 'normal'
  noise_std: 0.1

Ant-v3:
  <<: *mujoco-defaults

Hopper-v3:
  <<: *mujoco-defaults

Walker2d-v3:
  <<: *mujoco-defaults

Humanoid-v3:
  <<: *mujoco-defaults
  n_timesteps: !!float 2e6

Swimmer-v3:
  <<: *mujoco-defaults
  gamma: 0.9999
  train_freq: 1
  gradient_steps: 1

AcrobotSwingupDMC-v0: &dmc-defaults
  policy: 'MlpPolicy'
  n_timesteps: !!float 1e6
  batch_size: 64
  policy_kwargs: "dict(net_arch=dict(pi=[300, 200], qf=[400, 300]))" 
  learning_rate: !!float 1e-4
  gamma: 0.99
  noise_type: 'ornstein-uhlenbeck'
  noise_std: 0.3

AcrobotSwingupSparseDMC-v0: 
    <<: *dmc-defaults

BallInCupDMC-v0: 
    <<: *dmc-defaults

CartpoleDMC-v0: 
    <<: *dmc-defaults

CartpoleSparseDMC-v0: 
    <<: *dmc-defaults

CartpoleSwingupDMC-v0: 
    <<: *dmc-defaults

CartpoleSwingupSparseDMC-v0: 
    <<: *dmc-defaults

CartpoleTwoPolesDMC-v0: 
    <<: *dmc-defaults

CartpoleThreePolesDMC-v0: 
    <<: *dmc-defaults

CheetahDMC-v0: 
    <<: *dmc-defaults

FingerSpinDMC-v0: 
    <<: *dmc-defaults

FingerTurnEasyDMC-v0: 
    <<: *dmc-defaults

FingerTurnHardDMC-v0: 
    <<: *dmc-defaults

FishSwimDMC-v0: 
    <<: *dmc-defaults

FishUprightDMC-v0: 
    <<: *dmc-defaults

HopperDMC-v0: 
    <<: *dmc-defaults

HopperStandDMC-v0: 
    <<: *dmc-defaults

HumanoidRunDMC-v0: 
    <<: *dmc-defaults

HumanoidStandDMC-v0: 
    <<: *dmc-defaults

HumanoidWalkDMC-v0: 
    <<: *dmc-defaults

HumanoidRunPureStateDMC-v0: 
    <<: *dmc-defaults

ManipulatorBringBallDMC-v0: 
    <<: *dmc-defaults

ManipulatorBringPegDMC-v0: 
    <<: *dmc-defaults

ManipulatorInsertBallDMC-v0: 
    <<: *dmc-defaults

ManipulatorInsertPegDMC-v0: 
    <<: *dmc-defaults

PendulumDMC-v0: 
    <<: *dmc-defaults

PointMassDMC-v0: 
    <<: *dmc-defaults

PointMassHardDMC-v0: 
    <<: *dmc-defaults

ReacherDMC-v0: 
    <<: *dmc-defaults

ReacherHardDMC-v0: 
    <<: *dmc-defaults

Swimmer15DMC-v0: 
    <<: *dmc-defaults

Swimmer6DMC-v0: 
    <<: *dmc-defaults

WalkerRunDMC-v0: 
    <<: *dmc-defaults

WalkerStandDMC-v0: 
    <<: *dmc-defaults

WalkerDMC-v0: 
    <<: *dmc-defaults
